'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard1
    
    '''<summary>
    '''alertWelcome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents alertWelcome As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblUserCompany control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserCompany As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlAccntTitleAPV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccntTitleAPV As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccntTitleYearAPV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccntTitleYearAPV As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccntTitleMonthGM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccntTitleMonthGM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccntTitleYearGM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccntTitleYearGM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccntTitleSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccntTitleSales As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlAccntTitleYearSales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccntTitleYearSales As Global.System.Web.UI.WebControls.DropDownList
End Class
